import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN
import math


angles = []


angles = range(0, 360, 10)
for index, angle in enumerate(angles):
	angles[index] =  math.radians(angle)

xPoints = []

for x in angles:
	xPoints.append(10*math.cos(x))
	
	
yPoints = []

for x in angles:
	yPoints.append(10*math.sin(x))

pointlist = []

for index, point in enumerate(xPoints):
	pointlist.append(Point.ByCoordinates(point,yPoints[index],0))
	
	
#Assign your output to the OUT variable.
OUT = pointlist
